// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: broadcast/proto/broadcast.proto

package proto

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BroadcastMsg is a simple broadcast message.
type BroadcastMsg struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data   string                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Sender uint32                 `protobuf:"varint,2,opt,name=sender"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BroadcastMsg) Reset() {
	*x = BroadcastMsg{}
	mi := &file_broadcast_proto_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMsg) ProtoMessage() {}

func (x *BroadcastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BroadcastMsg) GetData() string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return ""
}

func (x *BroadcastMsg) GetSender() uint32 {
	if x != nil {
		return x.xxx_hidden_Sender
	}
	return 0
}

func (x *BroadcastMsg) SetData(v string) {
	x.xxx_hidden_Data = v
}

func (x *BroadcastMsg) SetSender(v uint32) {
	x.xxx_hidden_Sender = v
}

type BroadcastMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data   string
	Sender uint32
}

func (b0 BroadcastMsg_builder) Build() *BroadcastMsg {
	m0 := &BroadcastMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Sender = b.Sender
	return m0
}

// BroadcastAck acknowledges receipt of a broadcast message.
type BroadcastAck struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NodeId      uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId"`
	xxx_hidden_Delivered   bool                   `protobuf:"varint,2,opt,name=delivered"`
	xxx_hidden_ForwardedTo uint32                 `protobuf:"varint,3,opt,name=forwarded_to,json=forwardedTo"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BroadcastAck) Reset() {
	*x = BroadcastAck{}
	mi := &file_broadcast_proto_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastAck) ProtoMessage() {}

func (x *BroadcastAck) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BroadcastAck) GetNodeId() uint32 {
	if x != nil {
		return x.xxx_hidden_NodeId
	}
	return 0
}

func (x *BroadcastAck) GetDelivered() bool {
	if x != nil {
		return x.xxx_hidden_Delivered
	}
	return false
}

func (x *BroadcastAck) GetForwardedTo() uint32 {
	if x != nil {
		return x.xxx_hidden_ForwardedTo
	}
	return 0
}

func (x *BroadcastAck) SetNodeId(v uint32) {
	x.xxx_hidden_NodeId = v
}

func (x *BroadcastAck) SetDelivered(v bool) {
	x.xxx_hidden_Delivered = v
}

func (x *BroadcastAck) SetForwardedTo(v uint32) {
	x.xxx_hidden_ForwardedTo = v
}

type BroadcastAck_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NodeId      uint32
	Delivered   bool
	ForwardedTo uint32
}

func (b0 BroadcastAck_builder) Build() *BroadcastAck {
	m0 := &BroadcastAck{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NodeId = b.NodeId
	x.xxx_hidden_Delivered = b.Delivered
	x.xxx_hidden_ForwardedTo = b.ForwardedTo
	return m0
}

var File_broadcast_proto_broadcast_proto protoreflect.FileDescriptor

const file_broadcast_proto_broadcast_proto_rawDesc = "" +
	"\n" +
	"\x1fbroadcast/proto/broadcast.proto\x12\tbroadcast\x1a\x1bgoogle/protobuf/empty.proto\x1a\fgorums.proto\":\n" +
	"\fBroadcastMsg\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\rR\x06sender\"h\n" +
	"\fBroadcastAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x1c\n" +
	"\tdelivered\x18\x02 \x01(\bR\tdelivered\x12!\n" +
	"\fforwarded_to\x18\x03 \x01(\rR\vforwardedTo2\x96\x01\n" +
	"\tBroadcast\x12B\n" +
	"\tBroadcast\x12\x17.broadcast.BroadcastMsg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12E\n" +
	"\vBroadcastQC\x12\x17.broadcast.BroadcastMsg\x1a\x17.broadcast.BroadcastAck\"\x04\xa0\xb5\x18\x01B&Z\x1fgorums/examples/broadcast/proto\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_broadcast_proto_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_broadcast_proto_broadcast_proto_goTypes = []any{
	(*BroadcastMsg)(nil),  // 0: broadcast.BroadcastMsg
	(*BroadcastAck)(nil),  // 1: broadcast.BroadcastAck
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_broadcast_proto_broadcast_proto_depIdxs = []int32{
	0, // 0: broadcast.Broadcast.Broadcast:input_type -> broadcast.BroadcastMsg
	0, // 1: broadcast.Broadcast.BroadcastQC:input_type -> broadcast.BroadcastMsg
	2, // 2: broadcast.Broadcast.Broadcast:output_type -> google.protobuf.Empty
	1, // 3: broadcast.Broadcast.BroadcastQC:output_type -> broadcast.BroadcastAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_broadcast_proto_broadcast_proto_init() }
func file_broadcast_proto_broadcast_proto_init() {
	if File_broadcast_proto_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broadcast_proto_broadcast_proto_rawDesc), len(file_broadcast_proto_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broadcast_proto_broadcast_proto_goTypes,
		DependencyIndexes: file_broadcast_proto_broadcast_proto_depIdxs,
		MessageInfos:      file_broadcast_proto_broadcast_proto_msgTypes,
	}.Build()
	File_broadcast_proto_broadcast_proto = out.File
	file_broadcast_proto_broadcast_proto_goTypes = nil
	file_broadcast_proto_broadcast_proto_depIdxs = nil
}
