// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.11.0-devel
// 	protoc            v6.33.2
// source: broadcast/proto/broadcast.proto

package proto

import (
	gorums "github.com/relab/gorums"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorums.EnforceVersion(11 - gorums.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorums.EnforceVersion(gorums.MaxVersion - 11)
)

// Type aliases for important Gorums types to make them more accessible
// from user code already interacting with the generated code.
type (
	Configuration = gorums.Configuration
	Manager       = gorums.Manager
	Node          = gorums.Node
	NodeContext   = gorums.NodeContext
	ConfigContext = gorums.ConfigContext
)

// Use the aliased types to add them to the reserved identifiers list.
// This prevents users from defining message types with these names.
var (
	_ = (*Configuration)(nil)
	_ = (*Manager)(nil)
	_ = (*Node)(nil)
	_ = (*NodeContext)(nil)
	_ = (*ConfigContext)(nil)
)

// NewManager returns a new Manager for managing connection to nodes added
// to the manager. This function accepts manager options used to configure
// various aspects of the manager.
func NewManager(opts ...gorums.ManagerOption) *Manager {
	return gorums.NewManager(opts...)
}

// NewConfiguration returns a configuration based on the provided list of nodes.
// Nodes can be supplied using WithNodes or WithNodeList.
// A new configuration can also be created from an existing configuration
// using the Add, Union, Remove, Difference, Extend, and WithoutErrors methods.
func NewConfiguration(mgr *Manager, opt gorums.NodeListOption) (Configuration, error) {
	return gorums.NewConfiguration(mgr, opt)
}

// NewConfig returns a new [Configuration] based on the provided [gorums.Option]s.
// It accepts exactly one [gorums.NodeListOption] and multiple [gorums.ManagerOption]s.
// You may use this function to create the initial configuration for a new manager.
//
// Example:
//
//		cfg, err := NewConfig(
//		    gorums.WithNodeList([]string{"localhost:8080", "localhost:8081", "localhost:8082"}),
//	        gorums.WithDialOptions(grpc.WithTransportCredentials(insecure.NewCredentials())),
//		)
//
// This is a convenience function for creating a configuration without explicitly
// creating a manager first. However, the manager can be accessed using the
// [Configuration.Manager] method. This method should only be used once since it
// creates a new manager; if a manager already exists, use [NewConfiguration]
// instead, and provide the existing manager as the first argument.
func NewConfig(opts ...gorums.Option) (Configuration, error) {
	return gorums.NewConfig(opts...)
}

// AsyncBroadcastAck is a future for async quorum calls returning *BroadcastAck.
type AsyncBroadcastAck = *gorums.Async[*BroadcastAck]

// CorrectableBroadcastAck is a correctable object for quorum calls returning *BroadcastAck.
type CorrectableBroadcastAck = *gorums.Correctable[*BroadcastAck]

// Reference imports to suppress errors if they are not otherwise used.
var _ emptypb.Empty

// Broadcast receives a message and relays it to all other nodes (no response).
func Broadcast(ctx *NodeContext, in *BroadcastMsg, opts ...gorums.CallOption) error {
	return gorums.Unicast(ctx, in, "broadcast.Broadcast.Broadcast", opts...)
}

// BroadcastQC is a quorum call that broadcasts and collects acknowledgments.
// Each node acknowledges receipt and forwards to others.
func BroadcastQC(ctx *ConfigContext, in *BroadcastMsg, opts ...gorums.CallOption) *gorums.Responses[*BroadcastAck] {
	return gorums.QuorumCall[*BroadcastMsg, *BroadcastAck](
		ctx, in, "broadcast.Broadcast.BroadcastQC",
		opts...,
	)
}

// Broadcast is the server-side API for the Broadcast Service
type BroadcastServer interface {
	Broadcast(ctx gorums.ServerCtx, request *BroadcastMsg)
	BroadcastQC(ctx gorums.ServerCtx, request *BroadcastMsg) (response *BroadcastAck, err error)
}

func RegisterBroadcastServer(srv *gorums.Server, impl BroadcastServer) {
	srv.RegisterHandler("broadcast.Broadcast.Broadcast", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*BroadcastMsg](in)
		impl.Broadcast(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("broadcast.Broadcast.BroadcastQC", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*BroadcastMsg](in)
		resp, err := impl.BroadcastQC(ctx, req)
		if err != nil {
			return nil, err
		}
		return gorums.NewResponseMessage(in, resp), nil
	})
}
