// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.11.0-devel
// 	protoc            v6.33.2
// source: simplex/proto/simplex.proto

package proto

import (
	gorums "github.com/relab/gorums"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorums.EnforceVersion(11 - gorums.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorums.EnforceVersion(gorums.MaxVersion - 11)
)

// Type aliases for important Gorums types to make them more accessible
// from user code already interacting with the generated code.
type (
	Configuration = gorums.Configuration
	Manager       = gorums.Manager
	Node          = gorums.Node
	NodeContext   = gorums.NodeContext
	ConfigContext = gorums.ConfigContext
)

// Use the aliased types to add them to the reserved identifiers list.
// This prevents users from defining message types with these names.
var (
	_ = (*Configuration)(nil)
	_ = (*Manager)(nil)
	_ = (*Node)(nil)
	_ = (*NodeContext)(nil)
	_ = (*ConfigContext)(nil)
)

// NewManager returns a new Manager for managing connection to nodes added
// to the manager. This function accepts manager options used to configure
// various aspects of the manager.
func NewManager(opts ...gorums.ManagerOption) *Manager {
	return gorums.NewManager(opts...)
}

// NewConfiguration returns a configuration based on the provided list of nodes.
// Nodes can be supplied using WithNodes or WithNodeList.
// A new configuration can also be created from an existing configuration
// using the Add, Union, Remove, Difference, Extend, and WithoutErrors methods.
func NewConfiguration(mgr *Manager, opt gorums.NodeListOption) (Configuration, error) {
	return gorums.NewConfiguration(mgr, opt)
}

// NewConfig returns a new [Configuration] based on the provided [gorums.Option]s.
// It accepts exactly one [gorums.NodeListOption] and multiple [gorums.ManagerOption]s.
// You may use this function to create the initial configuration for a new manager.
//
// Example:
//
//		cfg, err := NewConfig(
//		    gorums.WithNodeList([]string{"localhost:8080", "localhost:8081", "localhost:8082"}),
//	        gorums.WithDialOptions(grpc.WithTransportCredentials(insecure.NewCredentials())),
//		)
//
// This is a convenience function for creating a configuration without explicitly
// creating a manager first. However, the manager can be accessed using the
// [Configuration.Manager] method. This method should only be used once since it
// creates a new manager; if a manager already exists, use [NewConfiguration]
// instead, and provide the existing manager as the first argument.
func NewConfig(opts ...gorums.Option) (Configuration, error) {
	return gorums.NewConfig(opts...)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ emptypb.Empty

// Propose is multicast by the current leader to propose a new block
// that extends its view of the notarized blockchain.
func Propose(ctx *ConfigContext, in *ProposeMsg, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "simplex.SimplexNode.Propose", opts...)
}

// Vote is multicast by every node to cast a vote for a block (or for the
// dummy block when the 3Δ backup timer fires).
func Vote(ctx *ConfigContext, in *VoteMsg, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "simplex.SimplexNode.Vote", opts...)
}

// Finalize is multicast by a node when it advances to the next iteration,
// signalling that it has seen a notarized block at the current height.
func Finalize(ctx *ConfigContext, in *FinalizeMsg, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "simplex.SimplexNode.Finalize", opts...)
}

// NotarizedChain is multicast together with Finalize so that lagging nodes
// can fast-forward to the latest notarized blockchain.
func NotarizedChain(ctx *ConfigContext, in *NotarizedChainMsg, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "simplex.SimplexNode.NotarizedChain", opts...)
}

// SimplexNode is the server-side API for the SimplexNode Service
type SimplexNodeServer interface {
	Propose(ctx gorums.ServerCtx, request *ProposeMsg)
	Vote(ctx gorums.ServerCtx, request *VoteMsg)
	Finalize(ctx gorums.ServerCtx, request *FinalizeMsg)
	NotarizedChain(ctx gorums.ServerCtx, request *NotarizedChainMsg)
}

func RegisterSimplexNodeServer(srv *gorums.Server, impl SimplexNodeServer) {
	srv.RegisterHandler("simplex.SimplexNode.Propose", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*ProposeMsg](in)
		impl.Propose(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("simplex.SimplexNode.Vote", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*VoteMsg](in)
		impl.Vote(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("simplex.SimplexNode.Finalize", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*FinalizeMsg](in)
		impl.Finalize(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("simplex.SimplexNode.NotarizedChain", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*NotarizedChainMsg](in)
		impl.NotarizedChain(ctx, req)
		return nil, nil
	})
}
