// Package main implements the Simplex Byzantine fault-tolerant consensus
// protocol as a Gorums example.
//
// Simplex protocol reference: https://simplex.blog/protocol/
//
// The protocol runs in iterations h = 1, 2, 3, ...  In each iteration:
//  1. A timer set to 3Δ is started.  If it fires, the node votes for the dummy
//     block (a timeout vote).
//  2. The designated leader multicasts a Propose message with a new block
//     extending a notarized parent chain.
//  3. On receiving a valid proposal, a node multicasts a Vote for that block.
//  4. When a node sees ≥⌈2n/3⌉ votes for any block at height h, it considers
//     that block "notarized".  It then:
//     - Cancels the timer.
//     - Multicasts a Finalize message for height h.
//     - Multicasts its full notarized chain.
//     - Advances to iteration h+1.
//  5. When a node sees ≥⌈2n/3⌉ Finalize messages for height h, it permanently
//     confirms the transactions in the non-dummy notarized block at height h.
package main

import (
	"context"
	"crypto/sha256"
	"fmt"
	"log/slog"
	"strings"
	"sync"
	"time"

	"github.com/relab/gorums"
	pb "github.com/relab/gorums/examples/simplex/proto"
)

// delta is the assumed upper bound on network message delay.
// The backup timer fires after 3*delta seconds.
const delta = 100 * time.Millisecond

// Node is a Simplex consensus node.
// It implements the SimplexNodeServer interface generated by Gorums and
// drives the protocol by sending multicasts to its peers.
type Node struct {
	id  uint32               // 1-indexed node ID
	n   int                  // total cluster size
	cfg gorums.Configuration // outbound configuration for peer multicasts

	mu     sync.Mutex
	ctx    context.Context
	cancel context.CancelFunc
	height uint64             // current iteration height (starts at 1)
	chain  []*pb.Notarization // confirmed notarized blockchain; chain[i] is block at height i+1

	// votes[height][blockID] holds the set of VoteMsgs received for that block.
	votes map[uint64]map[string][]*pb.VoteMsg
	// voted[height] is true once we have sent a vote at that height.
	voted map[uint64]bool

	// finalizes[height][nodeID] is true once that node's Finalize was received.
	finalizes map[uint64]map[uint32]bool
	// finalized[height] is true once ≥⌈2n/3⌉ Finalize messages have been seen.
	finalized map[uint64]bool
	// notarized[height] holds the Notarization once a block is notarized.
	notarized map[uint64]*pb.Notarization

	timer      *time.Timer
	timerFired bool

	// finalizedTxs[height] holds the committed transactions for that height
	// (nil for dummy blocks).  FinalizedLog assembles them in height order.
	finalizedTxs map[uint64][]string

	// onFinalize is called after each height is finalized.
	onFinalize func(height uint64, txs []string)

	// Pending messages buffered while the node is at a lower height.
	pendingProposals map[uint64]*pb.ProposeMsg
	pendingVotes     map[uint64][]*pb.VoteMsg

	// Transaction pool: transactions waiting to be included in the next block.
	txMu   sync.Mutex
	txPool []string
}

// NewNode creates and returns a Simplex consensus node.
// id is the 1-indexed node ID, n is the cluster size, cfg is the outbound
// Gorums configuration for sending multicasts, and onFinalize (optional) is
// called whenever transactions are permanently confirmed.
func NewNode(id uint32, n int, cfg gorums.Configuration, onFinalize func(uint64, []string)) *Node {
	ctx, cancel := context.WithCancel(context.Background())
	return &Node{
		id:               id,
		n:                n,
		cfg:              cfg,
		ctx:              ctx,
		cancel:           cancel,
		height:           1,
		votes:            make(map[uint64]map[string][]*pb.VoteMsg),
		voted:            make(map[uint64]bool),
		finalizes:        make(map[uint64]map[uint32]bool),
		finalized:        make(map[uint64]bool),
		notarized:        make(map[uint64]*pb.Notarization),
		onFinalize:       onFinalize,
		finalizedTxs:     make(map[uint64][]string),
		pendingProposals: make(map[uint64]*pb.ProposeMsg),
		pendingVotes:     make(map[uint64][]*pb.VoteMsg),
	}
}

// Start enters the first iteration.  Call this after the Gorums server is
// serving and peer connections are established.
func (nd *Node) Start() {
	nd.mu.Lock()
	proposal := nd.enterIterationLocked(1)
	nd.mu.Unlock()
	nd.sendProposal(proposal)
}

// Stop halts the node and cancels all pending work.
func (nd *Node) Stop() {
	nd.mu.Lock()
	if nd.timer != nil {
		nd.timer.Stop()
	}
	nd.mu.Unlock()
	nd.cancel()
}

// AddTx enqueues a transaction for inclusion in the next proposed block.
func (nd *Node) AddTx(tx string) {
	nd.txMu.Lock()
	defer nd.txMu.Unlock()
	nd.txPool = append(nd.txPool, tx)
}

// FinalizedLog returns the confirmed transaction log in height order.
func (nd *Node) FinalizedLog() []string {
	nd.mu.Lock()
	defer nd.mu.Unlock()
	var result []string
	for h := uint64(1); h < nd.height; h++ {
		if txs, ok := nd.finalizedTxs[h]; ok {
			result = append(result, txs...)
		}
	}
	return result
}

// ID returns the node's 1-indexed ID.
func (nd *Node) ID() uint32 {
	return nd.id
}

// Height returns the node's current iteration height.
func (nd *Node) Height() uint64 {
	nd.mu.Lock()
	defer nd.mu.Unlock()
	return nd.height
}

// ─────────────────────────── protocol helpers ────────────────────────────────

// quorum returns the minimum votes or finalize messages required: ⌈2n/3⌉.
func quorum(n int) int {
	return (2*n + 2) / 3
}

// leaderForHeight returns the 1-indexed ID of the leader for iteration h.
// Leader selection uses a hash of h so leaders are spread across nodes.
func leaderForHeight(h uint64, n int) uint32 {
	data := fmt.Appendf(nil, "%d", h)
	hash := sha256.Sum256(data)
	// Combine three bytes for a 24-bit index to reduce bias.
	idx := uint64(hash[0]) | uint64(hash[1])<<8 | uint64(hash[2])<<16
	return uint32(idx%uint64(n)) + 1
}

// chainHash returns the SHA-256 hex digest of the ordered notarized chain.
// This is used as the ParentHash field of new blocks.
func chainHash(chain []*pb.Notarization) string {
	h := sha256.New()
	for _, n := range chain {
		b := n.GetBlock()
		fmt.Fprintf(h, "%d|%s|%s|", b.GetHeight(), b.GetParentHash(), strings.Join(b.GetTxs(), ","))
	}
	return fmt.Sprintf("%x", h.Sum(nil))
}

// blockID returns a unique string key for a block, used as a map key.
func blockID(b *pb.Block) string {
	if b == nil {
		return ""
	}
	return fmt.Sprintf("%d|%s|%s", b.GetHeight(), b.GetParentHash(), strings.Join(b.GetTxs(), ","))
}

// isDummyBlock reports whether b is a dummy block (height > 0, empty parent_hash).
func isDummyBlock(b *pb.Block) bool {
	return b != nil && b.GetHeight() > 0 && b.GetParentHash() == ""
}

// ─────────────────────────── core protocol ───────────────────────────────────

// enterIterationLocked sets up the state for iteration h and returns a
// ProposeMsg if this node is the leader of iteration h (nil otherwise).
// The caller is responsible for sending the returned proposal without holding
// nd.mu, so that it is delivered to peers before the 3Δ backup timer fires.
// Must be called with nd.mu held.
func (nd *Node) enterIterationLocked(h uint64) (proposal *pb.ProposeMsg) {
	nd.height = h
	nd.timerFired = false

	// Start the 3Δ backup timer.  On expiry the node votes for the dummy block.
	if nd.timer != nil {
		nd.timer.Stop()
	}
	nd.timer = time.AfterFunc(3*delta, func() {
		nd.mu.Lock()
		if nd.height != h || nd.timerFired {
			nd.mu.Unlock()
			return
		}
		nd.timerFired = true
		nd.mu.Unlock()
		// Vote for the dummy block (height h, empty ParentHash).
		nd.doSendVote(h, pb.Block_builder{Height: h}.Build())
	})

	// Build proposal if we are the leader.
	if leaderForHeight(h, nd.n) == nd.id {
		proposal = nd.buildProposalLocked(h)
	}

	// Replay any messages that arrived before we entered this iteration.
	nd.processPendingLocked(h)
	return proposal
}

// buildProposalLocked builds a ProposeMsg for height h.
// Must be called with nd.mu held.
func (nd *Node) buildProposalLocked(h uint64) *pb.ProposeMsg {
	// Drain the transaction pool (nd.txMu is always ordered after nd.mu).
	nd.txMu.Lock()
	txs := nd.txPool
	nd.txPool = nil
	nd.txMu.Unlock()

	parentHash := chainHash(nd.chain)
	block := pb.Block_builder{
		Height:     h,
		ParentHash: parentHash,
		Txs:        txs,
	}.Build()

	chain := make([]*pb.Notarization, len(nd.chain))
	copy(chain, nd.chain)

	return pb.ProposeMsg_builder{
		Height:   h,
		Block:    block,
		Chain:    chain,
		LeaderId: nd.id,
	}.Build()
}

// sendProposal multicasts a leader proposal if msg is non-nil.
func (nd *Node) sendProposal(msg *pb.ProposeMsg) {
	if msg == nil {
		return
	}
	cfgCtx := nd.cfg.Context(nd.ctx)
	if err := pb.Propose(cfgCtx, msg); err != nil && nd.ctx.Err() == nil {
		slog.Warn("propose send error", "node", nd.id, "height", msg.GetHeight(), "err", err)
	}
}

// advanceFromHeight is called when a block at height h becomes notarized.
// It atomically appends the notarization, advances nd.height to h+1, starts
// the new timer, and enters the next iteration, then (without the lock) sends
// the Finalize and NotarizedChain multicasts.
func (nd *Node) advanceFromHeight(h uint64, notarization *pb.Notarization) {
	nd.mu.Lock()
	if nd.height != h {
		nd.mu.Unlock()
		return // already advanced past h by another goroutine
	}

	// Extend the confirmed chain if needed.
	if uint64(len(nd.chain)) < h {
		nd.chain = append(nd.chain, notarization)
	}

	// Snapshot the chain for the outbound NotarizedChain message.
	chainSnapshot := make([]*pb.Notarization, len(nd.chain))
	copy(chainSnapshot, nd.chain)

	// Advance height and set up new iteration state.
	proposal := nd.enterIterationLocked(h + 1)
	nd.mu.Unlock()

	// Outbound sends without holding the lock; proposal first so peers can vote
	// before their backup timers fire.
	nd.sendProposal(proposal)
	nd.doSendFinalize(h)
	nd.doSendNotarizedChain(chainSnapshot)
}

// processPendingLocked replays buffered messages that arrived for height h.
// Returns any pending proposal for height h (or nil); the caller is
// responsible for sending it synchronously after releasing nd.mu.
// Must be called with nd.mu held.
func (nd *Node) processPendingLocked(h uint64) {
	if prop, ok := nd.pendingProposals[h]; ok {
		delete(nd.pendingProposals, h)
		go nd.handlePropose(prop)
	}
	if votes, ok := nd.pendingVotes[h]; ok {
		delete(nd.pendingVotes, h)
		for _, v := range votes {
			go nd.handleVote(v)
		}
	}
}

// ─────────────────────────── outbound senders ────────────────────────────────

// doSendVote multicasts a vote for block at height h.
func (nd *Node) doSendVote(h uint64, block *pb.Block) {
	msg := pb.VoteMsg_builder{Height: h, Block: block, VoterId: nd.id}.Build()
	cfgCtx := nd.cfg.Context(nd.ctx)
	if err := pb.Vote(cfgCtx, msg); err != nil && nd.ctx.Err() == nil {
		slog.Warn("vote send error", "node", nd.id, "height", h, "err", err)
	}
}

// doSendFinalize multicasts a Finalize message for height h.
func (nd *Node) doSendFinalize(h uint64) {
	msg := pb.FinalizeMsg_builder{Height: h, NodeId: nd.id}.Build()
	cfgCtx := nd.cfg.Context(nd.ctx)
	if err := pb.Finalize(cfgCtx, msg); err != nil && nd.ctx.Err() == nil {
		slog.Warn("finalize send error", "node", nd.id, "height", h, "err", err)
	}
}

// doSendNotarizedChain multicasts the full notarized chain.
func (nd *Node) doSendNotarizedChain(chain []*pb.Notarization) {
	msg := pb.NotarizedChainMsg_builder{Chain: chain}.Build()
	cfgCtx := nd.cfg.Context(nd.ctx)
	if err := pb.NotarizedChain(cfgCtx, msg); err != nil && nd.ctx.Err() == nil {
		slog.Warn("chain send error", "node", nd.id, "err", err)
	}
}

// ─────────────────────────── Gorums RPC handlers ─────────────────────────────

// tryFinalizeLocked checks whether height h can now be finalized, i.e.,
// both ≥⌈2n/3⌉ Finalize messages have been seen AND a notarized block exists.
// On success it marks the height finalized, appends transactions to nd.log,
// and returns the transactions for the caller to pass to onFinalize.
// Returns nil when conditions are not yet met or if the block is a dummy.
// Must be called with nd.mu held.
func (nd *Node) tryFinalizeLocked(h uint64) []string {
	if nd.finalized[h] {
		return nil
	}
	if len(nd.finalizes[h]) < quorum(nd.n) {
		return nil
	}
	n, ok := nd.notarized[h]
	if !ok {
		return nil
	}
	nd.finalized[h] = true
	if isDummyBlock(n.GetBlock()) {
		return nil
	}
	txs := n.GetBlock().GetTxs()
	nd.finalizedTxs[h] = txs
	return txs
}

// Propose handles an incoming leader proposal.
func (nd *Node) Propose(ctx gorums.ServerCtx, req *pb.ProposeMsg) {
	ctx.Release()
	nd.handlePropose(req)
}

func (nd *Node) handlePropose(req *pb.ProposeMsg) {
	h := req.GetHeight()

	nd.mu.Lock()
	if h < nd.height {
		nd.mu.Unlock()
		return // already past this height
	}
	if h > nd.height {
		// Buffer the proposal; we'll replay it when we reach height h.
		if _, exists := nd.pendingProposals[h]; !exists {
			nd.pendingProposals[h] = req
		}
		nd.mu.Unlock()
		return
	}
	// h == nd.height: validate and vote.

	// Only vote once per height.
	if nd.voted[h] {
		nd.mu.Unlock()
		return
	}
	// Verify the proposal comes from the expected leader.
	if req.GetLeaderId() != leaderForHeight(h, nd.n) {
		nd.mu.Unlock()
		return
	}
	// Verify the block's height field.
	if req.GetBlock().GetHeight() != h {
		nd.mu.Unlock()
		return
	}
	// Verify the parent chain has the correct length (h-1 notarizations).
	if uint64(len(req.GetChain())) != h-1 {
		nd.mu.Unlock()
		return
	}
	// Verify ParentHash matches the hash of the proposed parent chain.
	if req.GetBlock().GetParentHash() != chainHash(req.GetChain()) {
		nd.mu.Unlock()
		return
	}

	nd.voted[h] = true
	block := req.GetBlock()
	nd.mu.Unlock()

	nd.doSendVote(h, block)
}

// Vote handles an incoming vote message.
func (nd *Node) Vote(ctx gorums.ServerCtx, req *pb.VoteMsg) {
	ctx.Release()
	nd.handleVote(req)
}

func (nd *Node) handleVote(req *pb.VoteMsg) {
	h := req.GetHeight()

	nd.mu.Lock()
	if h < nd.height {
		nd.mu.Unlock()
		return
	}
	if h > nd.height {
		nd.pendingVotes[h] = append(nd.pendingVotes[h], req)
		nd.mu.Unlock()
		return
	}
	// h == nd.height: record vote and check for quorum.

	bid := blockID(req.GetBlock())
	if nd.votes[h] == nil {
		nd.votes[h] = make(map[string][]*pb.VoteMsg)
	}
	// Deduplicate: one vote per voter per block.
	for _, existing := range nd.votes[h][bid] {
		if existing.GetVoterId() == req.GetVoterId() {
			nd.mu.Unlock()
			return
		}
	}
	nd.votes[h][bid] = append(nd.votes[h][bid], req)

	// Check for vote quorum.
	if len(nd.votes[h][bid]) >= quorum(nd.n) {
		if _, already := nd.notarized[h]; !already {
			votes := make([]*pb.VoteMsg, len(nd.votes[h][bid]))
			copy(votes, nd.votes[h][bid])
			notarization := pb.Notarization_builder{
				Block: req.GetBlock(),
				Votes: votes,
			}.Build()
			nd.notarized[h] = notarization
			// A newly notarized block may satisfy a pending finalization.
			txs := nd.tryFinalizeLocked(h)
			nd.mu.Unlock()
			if nd.onFinalize != nil && len(txs) > 0 {
				nd.onFinalize(h, txs)
			}
			nd.advanceFromHeight(h, notarization)
			return
		}
	}
	nd.mu.Unlock()
}

// Finalize handles an incoming finalize message.
func (nd *Node) Finalize(ctx gorums.ServerCtx, req *pb.FinalizeMsg) {
	ctx.Release()
	nd.handleFinalize(req)
}

func (nd *Node) handleFinalize(req *pb.FinalizeMsg) {
	h := req.GetHeight()
	nodeID := req.GetNodeId()

	nd.mu.Lock()
	if nd.finalized[h] {
		nd.mu.Unlock()
		return // already finalized
	}
	if nd.finalizes[h] == nil {
		nd.finalizes[h] = make(map[uint32]bool)
	}
	nd.finalizes[h][nodeID] = true
	txs := nd.tryFinalizeLocked(h)
	nd.mu.Unlock()

	if nd.onFinalize != nil && len(txs) > 0 {
		nd.onFinalize(h, txs)
	}
}

// NotarizedChain handles an incoming notarized chain, allowing the node to
// fast-forward if the received chain is longer than the local one.
func (nd *Node) NotarizedChain(ctx gorums.ServerCtx, req *pb.NotarizedChainMsg) {
	ctx.Release()
	nd.handleNotarizedChain(req)
}

func (nd *Node) handleNotarizedChain(req *pb.NotarizedChainMsg) {
	incoming := req.GetChain()
	incomingLen := uint64(len(incoming))
	if incomingLen == 0 {
		return
	}

	nd.mu.Lock()
	if incomingLen <= uint64(len(nd.chain)) {
		nd.mu.Unlock()
		return // we already have an equal or longer chain
	}
	// Adopt the longer incoming chain.
	nd.chain = make([]*pb.Notarization, incomingLen)
	copy(nd.chain, incoming)
	startHeight := nd.height
	nd.mu.Unlock()

	// Advance through each height covered by the new chain.
	for h := startHeight; h <= incomingLen; h++ {
		nd.mu.Lock()
		if nd.height != h {
			nd.mu.Unlock()
			break // another goroutine already advanced further
		}
		notarization := nd.chain[h-1]
		var txsToFinalize []string
		if _, already := nd.notarized[h]; !already {
			nd.notarized[h] = notarization
			// A newly notarized block may satisfy a pending finalization.
			txsToFinalize = nd.tryFinalizeLocked(h)
		}
		nd.mu.Unlock()
		if nd.onFinalize != nil && len(txsToFinalize) > 0 {
			nd.onFinalize(h, txsToFinalize)
		}
		nd.advanceFromHeight(h, notarization)
	}
}
